### PR TITLE
Enable xdebug remote debugging and add phpMyAdmin

### PR DESCRIPTION
**Pull request by agathver**
Adds phpMyAdmin and [xdebug remote debugging](https://xdebug.org/docs/remote) to ansible. Only installed in Vagrant.

phpMyAdmin can be accessed through http://pma.librecores.devel

### CODE REVIEW

**Comment by imphil** [comment]
- Please add a note on the developer documentation about xdebug remote debugging.
- On PMA: Isn't the easyadmin bundle which we already integrate in Vagrant doing the job? PMA is kind of the ugly kid on the block from the last PHP decade; however, if its something which makes you productive, I'm not against it -- let's just make sure that the existing tools (easyadmin bundle) are not sufficient.

**Comment by agathver** [comment]
>Isn't the easyadmin bundle which we already integrate in Vagrant doing the job?

It allows to take dumps, run arbitrary SQL queries easily.

>let's just make sure that the existing tools (easyadmin bundle) are not sufficient.

PMA is made to interact with a database, EasyAdmin is geared for creating a dashboard like application with integrity enforcement etc. It is for editing data in production. It doesn't allow to drop all rows without reference checking or inspect raw database values that easily, which are needed while testing migrations.

On a side note: May be EasyAdmin should be added to the production version to allow user account moderation, project reassignment or other admin level tasks.

**Comment by imphil** [comment]
OK. Then please add the docs for xdebug and where to find PMA and this one is ready to go.

**Comment by imphil** [comment]
@agathver while writing the missing documentation for this PR, i saw that the commits are missing the file 99-librecores.ini, the xdebug template. Could you add that and then I'll add the documentation for it?

**Comment by imphil** [comment]
Ah, never mind, I just missed the file yesterday. All good @agathver !

**Comment by agathver** [comment]
@imphil Currently busy with exams will make changes after a week.

**Comment by imphil** [comment]
@agathver I already included the documentation changes and merged the PR. Thanks!

**Pull request merged**
