### PR TITLE
Upgrade to Symfony 3.3 - use new service and controller features

### PR DESCRIPTION
**Pull request by annika1**
Hi @imphil ,
here the second pull request to the issue #195 for the Symfony 3.3 upgrade. Is there a way to only request the important last commit (without my merge commits)?

### CODE REVIEW

**Comment by imphil** [comment]
You can rebase your code on top of the current master branch by running

~~~
git rebase origin/master
~~~

This way all merge commits should be gone. Note, however, that you'll need to force-push (`git push -f`) to this branch after this operation.

**Comment by annika1** [comment]
Ich have cleaned the commits. Thank you @imphil for the git rebase tip! 
If you have time take a look on it.

**Comment by imphil** [comment]
@annika1 sorry it took so long, today was the last day of the Google Summer of Code application period, and we got flooded by mails in the last couple of weeks.

I had a look at your PR and I found some places where it doesn't work yet. At least the following diff is required https://gist.github.com/imphil/1b18849ba211f3bb412bf35205cf5b1a, but there might be more. Honestly, I got a bit lost in all this new auto* stuff and deprecation warnings which will deprecate itself in the next Symfony version ...

So could you do the following:
- Apply the linked patch.
- Recreate your Vagrant instance, and check if you can
  - log in using the the test credentials (user test, password test)
  - add a new project using a Git URL
  - edit the settings of this new project

If that works, let's merge this for now, as your PR clearly improves things. It's a first step on the path towards Symfony 4, and indeed a very good one! We can then step by step remove more service definitions and rely on more auto-registration, auto-wiring and auto-tagging.

**Comment by imphil** [comment]
@agathver do you have more experience with all this new and fancy auto* stuff? If you find time, could you please have a look at the PR? That would help me a lot.

**Comment by imphil** [comment]
Ah, and there's another thing: when creating a new project we get the following error messages in `/var/log/syslog` inside vagrant:

~~~

Mar 27 19:21:59 vagrant php[18769]: 19:21:59 ERROR     [console] Error thrown while running command "rabbitmq:consumer -w -l 256 -m 250 update_project_info". Message: "Call to undefined method Exercise\HTMLPurifierBundle\Form\HTMLPurifierTransformer::purify()" ["error" => Error { …},"command" => "rabbitmq:consumer -w -l 256 -m 250 update_project_info","message" => "Call to undefined method Exercise\HTMLPurifierBundle\Form\HTMLPurifierTransformer::purify()"] []
Mar 27 19:21:59 vagrant php[18769]: PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\UndefinedMethodException: Attempted to call an undefined method named "purify" of class "Exercise\HTMLPurifierBundle\Form\HTMLPurifierTransformer". in /var/www/lc/site/src/Librecores/ProjectRepoBundle/Util/MarkupToHtmlConverter.php:158
Mar 27 19:21:59 vagrant php[18769]: Stack trace:
Mar 27 19:21:59 vagrant php[18769]: #0 /var/www/lc/site/src/Librecores/ProjectRepoBundle/Util/MarkupToHtmlConverter.php(66): Librecores\ProjectRepoBundle\Util\MarkupToHtmlConverter->sanitizeHtml('<h1><em>mor1kx<...')
Mar 27 19:21:59 vagrant php[18769]: #1 /var/www/lc/site/src/Librecores/ProjectRepoBundle/RepoCrawler/GitRepoCrawler.php(332): Librecores\ProjectRepoBundle\Util\MarkupToHtmlConverter->convertFile('/tmp/lc-gitrepo...')
Mar 27 19:21:59 vagrant php[18769]: #2 /var/www/lc/site/src/Librecores/ProjectRepoBundle/RepoCrawler/GitRepoCrawler.php(152): Librecores\ProjectRepoBundle\RepoCrawler\GitRepoCrawler->getDescriptionSafeHtml()
Mar 27 19:21:59 vagrant php[18769]: #3 /var/www/lc/site/src/Librecores/ProjectRepoBundle/RepoCrawler/GithubRepoCrawler.php(88): Librecores\ProjectRepoBundle\RepoCrawler\GitRepoCrawler->updateProject()
Mar 27 19:21:59 vagrant php[18769]: #4 /var/www/lc/site/src/Librecore in /var/www/lc/site/src/Librecores/ProjectRepoBundle/Util/MarkupToHtmlConverter.php on line 158
~~~

This can be fixed by 

```diff
diff --git a/site/src/Librecores/ProjectRepoBundle/Util/MarkupToHtmlConverter.php b/site/src/Librecores/ProjectRepoBundle/Util/MarkupToHtmlConverter.php
index 4544718..3bf014e 100644
--- a/site/src/Librecores/ProjectRepoBundle/Util/MarkupToHtmlConverter.php
+++ b/site/src/Librecores/ProjectRepoBundle/Util/MarkupToHtmlConverter.php
@@ -4,7 +4,6 @@ namespace Librecores\ProjectRepoBundle\Util;
 use Symfony\Component\Process\Process;
 use Psr\Log\LoggerInterface;
 use Symfony\Component\Process\Exception\ProcessFailedException;
-use Symfony\Component\Form\DataTransformerInterface;
 
 /**
  * Convert text written in a markup language to safe HTML
@@ -33,7 +32,8 @@ class MarkupToHtmlConverter
     private $logger;
     private $htmlPurifier;
 
-    public function __construct(LoggerInterface $logger, DataTransformerInterface $htmlPurifier)
+    public function __construct(LoggerInterface $logger,
+                                \HTMLPurifier $htmlPurifier)
     {
         $this->logger = $logger;
         $this->htmlPurifier = $htmlPurifier;
```

but I'm not convinced that this is a good solution. The better solution might be to leave the injection of the DataTransformerInterface and use the `reverseTransform()` method instead of `purify()`.

**Comment by annika1** [comment]
@imphil I will take a look on this the next days. Thank you for the feedback!

**Comment by agathver** [comment]
@annika1 I would like to pick up this issue right where you left. Our symfony is woefully out of date.

**Comment by imphil** [comment]
I didn't check too closely, but most of our code is actually deprecation-free at the moment. We're running Symfony 3.4 LTS, so not really out of date at all.

**Comment by annika1** [comment]
Feel free to pick it up.

**Comment by imphil** [comment]
This work has now gone in through other PRs. Thanks for your initial work on it @annika1!

**Pull request closed without merging**
