### PR TITLE
Project page: Add badges for projects being hosted on GitHub

### PR DESCRIPTION
**Pull request by oleg-nenashev**
Addresses #80

The PR provides the following badges:

* Number of stars (if SourceRepo URL is GitHub)
* Number of open pull requests (if SourceRepo URL is GitHub)
* Number of open issues (if Issue Tracker URL is GitHub)

**Disclaimer**: The code below likely contains my first code lines in PHP ever. Will appreciate any reviews regarding making the code compliant with project standards.

Example:
screen shot 2016-12-18 at 18 01 45

CC @asb and @berndca

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
As we discussed in #80, this approach makes the user web browser to send GitHub requests and to consume it's API limit. It's not the best solution. Likely a kind of the background crawler is required.

**Comment by eliaskousk** [comment]
Thank you @oleg-nenashev, that was a great first try on PHP. I improved the PR by adding Github util as a service in the container which is the recommended way of adding such things in Symfony. I also refactored the code and in general made everything Symfony friendly.

Looking at the changes you can see how a service is defined in YAML and retrieved from a controller and how to pass it static arguments (e.g the github.com and shield.io URLs). Dynamic arguments like things that a controller generates are best set by setter functions and not in the service's constructor (e.g the projects source repo and issue tracker url). Setting such parameters for end user code is a little overkill (github.com would never change!) but I thought it was a good example on parameter passing.

I don't have access and couldn't push to @oleg-nenashev's  fork in order for it to show here and so I pushed the commit to a separate branch. You can find it on 22f9e34.

**Comment by oleg-nenashev** [comment]
@eliaskousk Just create a new PR for your fork. Thanks for adjusting it

**Comment by eliaskousk** [comment]
Closing this

**Pull request closed without merging**
