### PR TITLE
Add autofocus attribute to set keyboard focus to search bar

### PR DESCRIPTION
**Pull request by jschram**
As mentioned in issue #184.

This issue was a bit scarce on information, let me know if there's any other search boxes that need this fix.

### CODE REVIEW

**Comment by imphil** [comment]
Thanks @jschram ! While at it, could you please also add the autofocus attribute on the search box on the search page itself? https://www.librecores.org/search

**Comment by jschram** [comment]
Sure, I've updated the PR

**Comment by imphil** [comment]
Thanks @jschram for this PR! Are you interested in further work on LibreCores? https://github.com/librecores/librecores-web/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3A%22good%20first%20bug%20%22 lists a couple of bugs (we can tag them "Hackoktoberfest" if needed of course.) Otherwise, just join https://gitter.im/librecores/Lobby and we'll find something to do :-)

**Comment by jschram** [comment]
You're welcome! When I find more spare time, I'll consider some more PR's :)

**Pull request merged**
