### PR TITLE
Symfony3

### PR DESCRIPTION
**Pull request by wallento**

### CODE REVIEW

**Comment by imphil** [comment]
This needs more work to move to the Symfony 3 directory structure, as described here: https://knpuniversity.com/screencast/symfony3-upgrade/new-dir-structure

**Comment by wallento** [comment]
I will take care of it

**Comment by wallento** [comment]
I hope it is ready now

**Comment by imphil** [comment]
Fixed a couple more code problems, squashed and merged. Thanks!

**Pull request merged**
